### ISSUE TITLE
[bug] 自动构建bug，main.spec not found.

### ISSUE THREAD

**Issue by Lafcadia** [lilingfengdev/PluginSearchEngine#6]
![main.spec not found.](https://github.com/lilingfengdev/PluginSearchEngine/assets/147896059/380a30eb-1406-401e-aaff-9f4e8aa4861b)

**Comment by aeroidesdev** [comment]
时间紧张，没来得及测试，大佬解决吧

**Comment by Lafcadia** [comment]
改成 nuitka 得了...
